### ISSUE TITLE
crash when resizing window

### ISSUE THREAD

**Issue by Be-ing** [mtytel/vital#3]
```
standalone/builds/linux on  main took 2s 
❯ gdb build/vial
GNU gdb (GDB) Fedora 10.1-2.fc33
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/vial...
(gdb) r
Starting program: /home/be/sw/vital/standalone/builds/linux/build/vial 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.32-3.fc33.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
JUCE v6.0.5
[New Thread 0x7ffff3ba4640 (LWP 72454)]
[New Thread 0x7ffff3316640 (LWP 72459)]
[Thread 0x7ffff3316640 (LWP 72459) exited]

Thread 2 "vial" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7ffff3ba4640 (LWP 72454)]
0x00007ffff76f2c4e in epoll_wait () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install alsa-lib-1.2.4-5.fc33.x86_64 bzip2-libs-1.0.8-4.fc33.x86_64 cyrus-sasl-lib-2.1.27-6.fc33.x86_64 dbus-libs-1.12.20-2.fc33.x86_64 fftw-devel-3.3.8-9.fc33.x86_64 freetype-2.10.4-1.fc33.x86_64 glib2-2.66.4-1.fc33.x86_64 keyutils-libs-1.6.1-1.fc33.x86_64 krb5-libs-1.18.2-29.fc33.x86_64 libX11-1.6.12-3.fc33.x86_64 libXau-1.0.9-4.fc33.x86_64 libXcursor-1.2.0-3.fc33.x86_64 libXext-1.3.4-4.fc33.x86_64 libXfixes-5.0.3-12.fc33.x86_64 libXinerama-1.1.4-6.fc33.x86_64 libXrender-0.9.10-12.fc33.x86_64 libblkid-2.36.1-1.fc33.x86_64 libbrotli-1.0.9-3.fc33.x86_64 libcom_err-1.45.6-4.fc33.x86_64 libcurl-7.71.1-8.fc33.x86_64 libffi-3.1-26.fc33.x86_64 libgcc-10.2.1-9.fc33.x86_64 libgcrypt-1.8.7-1.fc33.x86_64 libglvnd-1.3.2-2.fc33.x86_64 libglvnd-glx-1.3.2-2.fc33.x86_64 libgpg-error-1.41-1.fc33.x86_64 libmount-2.36.1-1.fc33.x86_64 libnghttp2-1.41.0-3.fc33.x86_64 libpng-1.6.37-6.fc33.x86_64 libpsl-0.21.1-2.fc33.x86_64 libsecret-0.20.4-1.fc33.x86_64 libselinux-3.1-2.fc33.x86_64 libssh-0.9.5-1.fc33.x86_64 libstdc++-10.2.1-9.fc33.x86_64 libunistring-0.9.10-9.fc33.x86_64 libxcb-1.13.1-5.fc33.x86_64 libzstd-1.4.7-1.fc33.x86_64 openldap-2.4.50-5.fc33.x86_64 openssl-libs-1.1.1i-1.fc33.x86_64 pcre-8.44-2.fc33.x86_64 pcre2-10.36-1.fc33.x86_64 sssd-client-2.4.0-4.fc33.x86_64 systemd-libs-246.7-2.fc33.x86_64 xz-libs-5.2.5-4.fc33.x86_64
(gdb) thread apply all bt

Thread 2 (Thread 0x7ffff3ba4640 (LWP 72454) "vial"):
#0  0x00007ffff76f2c4e in epoll_wait () at /lib64/libc.so.6
#1  0x00007ffff622d942 in impl_pollfd_wait (object=<optimized out>, pfd=<optimized out>, ev=0x7ffff3ba3a50, n_ev=<optimized out>, timeout=<optimized out>) at ../spa/plugins/support/system.c:154
#2  0x00007ffff62229bc in loop_iterate (object=0x3d7b8f8, timeout=-1) at ../spa/plugins/support/loop.c:291
#3  0x00007ffff6269bd0 in do_loop (user_data=0x1a51c60) at ../src/pipewire/data-loop.c:79
#4  0x00007ffff7d193f9 in start_thread () at /lib64/libpthread.so.0
#5  0x00007ffff76f2903 in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff6591880 (LWP 72437) "vial"):
#0  0x00007ffff7d1a9d7 in __pthread_clockjoin_ex () at /lib64/libpthread.so.0
#1  0x00007ffff626a133 in pw_data_loop_stop (loop=loop@entry=0x1a51c60) at ../src/pipewire/data-loop.c:242
#2  0x00007ffff626a360 in pw_data_loop_destroy (loop=0x1a51c60) at ../src/pipewire/data-loop.c:170
#3  0x00007ffff6264bf5 in pw_context_destroy (context=0x3d91d20) at ../src/pipewire/context.c:418
#4  0x00007ffff62ff10a in jack_client_close (client=0x3d77220) at ../pipewire-jack/src/pipewire-jack.c:2669
#5  0x0000000000cc0d3a in juce::jack_client_close(_jack_client*) (client=0x3d77220) at ../../../third_party/JUCE/modules/juce_audio_devices/native/juce_linux_JackAudio.cpp:57
#6  0x0000000000cd123f in juce::JackAudioIODeviceType::scanForDevices() (this=0x3d26fb0) at ../../../third_party/JUCE/modules/juce_audio_devices/native/juce_linux_JackAudio.cpp:615
#7  0x0000000000cc5758 in juce::AudioDeviceManager::scanDevicesIfNeeded() (this=0x188e778) at ../../../third_party/JUCE/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp:439
#8  0x0000000000cc4502 in juce::AudioDeviceManager::initialise(int, int, juce::XmlElement const*, bool, juce::String const&, juce::AudioDeviceManager::AudioDeviceSetup const*) (this=0x188e778, numInputChannelsNeeded=0, numOutputChannelsNeeded=2, xml=0x0, selectDefaultDeviceOnFailure=true, preferredDefaultDeviceName=..., preferredSetupOptions=0x0) at ../../../third_party/JUCE/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp:241
#9  0x0000000000dcbea4 in juce::AudioAppComponent::setAudioChannels(int, int, juce::XmlElement const*) (this=0x188e6b0, numInputChannels=0, numOutputChannels=2, xml=0x0) at ../../../third_party/JUCE/modules/juce_audio_utils/gui/juce_AudioAppComponent.cpp:70
#10 0x000000000078db26 in SynthEditor::SynthEditor(bool) (this=0x188e6b0, use_gui=true) at ../../../src/standalone/synth_editor.cpp:35
#11 0x0000000000790b68 in SynthApplication::MainWindow::MainWindow(juce::String const&, bool) (this=0x1851700, name=..., visible=true) at ../../../src/standalone/main.cpp:110
#12 0x0000000000795a56 in std::make_unique<SynthApplication::MainWindow, juce::String const, bool&>(juce::String const&&, bool&) () at /usr/include/c++/10/bits/unique_ptr.h:962
#13 0x00000000007943f0 in SynthApplication::initialise(juce::String const&) (this=0x18512e0, command_line=...) at ../../../src/standalone/main.cpp:498
#14 0x0000000000eebd0e in juce::JUCEApplicationBase::initialiseApp() (this=0x18512e0) at ../../../third_party/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:297
#15 0x0000000001070286 in juce::JUCEApplication::initialiseApp() (this=0x18512e0) at ../../../third_party/JUCE/modules/juce_gui_basics/application/juce_Application.cpp:92
#16 0x0000000000eebbc9 in juce::JUCEApplicationBase::main() () at ../../../third_party/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:256
#17 0x0000000000eebb0a in juce::JUCEApplicationBase::main(int, char const**) (argc=1, argv=0x7fffffffdb28) at ../../../third_party/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:240
#18 0x000000000078d2ca in main(int, char**) (argc=1, argv=0x7fffffffdb28) at ../../../src/standalone/main.cpp:539
```

**Comment by Be-ing** [comment]
I can't test whether this is a bug in PipeWire or a bug in Vital because I can't compare it to JACK due to #4.

**Comment by tank-trax** [comment]
do you have the jack2-dev installed?
